# Using the designer, it makes an interconnected web of layouts much simpler to do.
# in virtual environment 
# pyqt5-tools designer
# pyuic5 -x your_ui.ui -o your_output.py

from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtGui import QIcon, QFont
from PyQt5.QtCore import QThread, pyqtSignal


class Ui_Goomba(object):
    # colors
    background = "background-color:rgba(52, 73, 94,1.0)"  #2C3E50
    light_brown = "color:rgba(156,118,54,156);"  #9C7636
    brown = "color:rgba(79,66,43,79)"  #4F422B
    light_blue = "color:rgba(70,113,156,156)"  #46719C
    gray_blue = "color:rgba(101,128,156,156)"  #65809C
    red = "color:rgba(201,74,50,201)"  #C94A32
    text = "color:rgb(236, 240, 241)"

    pwr_style = "QPushButton {background-color:rgb(26, 188, 156); color:rgb(236, 240, 241)}"
    run = "QPushButton {background-color:rgb(46, 204, 113); color:rgb(236, 240, 241)}"
    pause = "QPushButton {background-color:rgb(231, 76, 60); color:rgb(236, 240, 241)}"


    last = False
    pwr_state = ""

    def setupUi(self, Goomba):
        Goomba.setObjectName("Goomba")
        Goomba.resize(600, 450)
        Goomba.setMinimumSize(QtCore.QSize(600, 450))
        Goomba.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setItalic(True)
        Goomba.setWindowIcon(QIcon("goomba_icon.png"))
        Goomba.setFont(font)
        Goomba.setWindowTitle("Goomba_GUI")
        Goomba.setStyleSheet("QWidget {background-color:rgba(52, 73, 94,1.0)}\n"
"QLabel {\n"
"color:rgb(236, 240, 241);\n"
"}")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Goomba)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Goomba)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.line_17 = QtWidgets.QFrame(Goomba)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_4.addWidget(self.line_17)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_7 = QtWidgets.QFrame(Goomba)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(Goomba)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 1, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(Goomba)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 1, 4, 1, 1)
        self.line_11 = QtWidgets.QFrame(Goomba)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 0, 3, 1, 1)
        self.line_12 = QtWidgets.QFrame(Goomba)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 2, 3, 1, 1)
        self.line_8 = QtWidgets.QFrame(Goomba)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.line_13 = QtWidgets.QFrame(Goomba)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 0, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(Goomba)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 2, 1, 1, 1)
        self.line_15 = QtWidgets.QFrame(Goomba)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(Goomba)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(10)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.line_5 = QtWidgets.QFrame(Goomba)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_6 = QtWidgets.QFrame(Goomba)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Goomba)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("")
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(Goomba)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("background-color:rgba(201,74,50,201)")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.line_3 = QtWidgets.QFrame(Goomba)
        self.line_3.setLineWidth(10)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(Goomba)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.line_16 = QtWidgets.QFrame(Goomba)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout.addWidget(self.line_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(Goomba)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12, 0, QtCore.Qt.AlignRight)
        self.label_15 = QtWidgets.QLabel(Goomba)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Goomba)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(Goomba)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.listWidget = QtWidgets.QListWidget(Goomba)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.listWidget.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("color:rgb(236, 240, 241);\n"
"background-color:rgba(70,113,156,156)")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_6.addWidget(self.listWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.buttonBox = QtWidgets.QDialogButtonBox(Goomba)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.buttonBox.setFont(font)
        self.buttonBox.setStyleSheet("color:rgb(236, 240, 241)")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_6.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter)
        self.line_4 = QtWidgets.QFrame(Goomba)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setLineWidth(10)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pwr = QtWidgets.QPushButton(Goomba)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pwr.sizePolicy().hasHeightForWidth())
        self.pwr.setSizePolicy(sizePolicy)
        self.pwr.setMinimumSize(QtCore.QSize(75, 75))
        self.pwr.setMaximumSize(QtCore.QSize(75, 75))
        self.pwr.setSizeIncrement(QtCore.QSize(2, 2))
        self.pwr.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.pwr.setFont(font)
        self.pwr.setStyleSheet(self.pwr_style)
        self.pwr.setWhatsThis("")
        self.pwr.setIcon(QIcon('power_icon.png'))
        self.pwr.setIconSize(QtCore.QSize(50, 50))
        self.pwr.setObjectName("pwr")
        self.verticalLayout_2.addWidget(self.pwr, 0, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(Goomba)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Goomba)
        QtCore.QMetaObject.connectSlotsByName(Goomba)
        self.pwr.clicked.connect(self.toggle)

    def toggle(self):  # on pwr button click this is called
        if self.last is False:
            self.label_14.setText("Running")
            pwr_style = self.run
            self.pwr_state = True  # gives go signal to bot
        elif self.last is True:
            self.label_14.setText("Paused")
            pwr_style = self.pause
            self.pwr_state = False
        self.last = not self.last
        self.pwr.setStyleSheet(pwr_style)
        return self.pwr_state
    
    def background_process(self):  # called when widget does something
        self.worker = WorkerThread()  
        self.worker.start()  # executes run() in workerthread
        self.worker.finished.connect(self.evt_finished)  # signal to communicate between threads
        self.worker.update_progress.connect(self.evt_update_progress)
    
    def evt_finished(self):
        # do stuff on signal that process is done

    def evt_upgrade_progress(self):  # called when we receive a signal from other process
        self.

    def retranslateUi(self, Goomba):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("Goomba", "Sonars"))
        self.label_3.setText(_translate("Goomba", "Left"))
        self.label_8.setText(_translate("Goomba", "123"))
        self.label_7.setText(_translate("Goomba", "123"))
        self.label_6.setText(_translate("Goomba", "234"))
        self.label_5.setText(_translate("Goomba", "Right"))
        self.label_4.setText(_translate("Goomba", "Front"))
        self.label_9.setText(_translate("Goomba", "Cliff Detection"))
        self.label_10.setText(_translate("Goomba", "123"))
        self.label_11.setText(_translate("Goomba", "False"))
        self.label.setText(_translate("Goomba", "Angle"))
        self.label_12.setText(_translate("Goomba", "123"))
        self.label_15.setText(_translate("Goomba", "Degrees"))
        self.label_13.setText(_translate("Goomba", "State"))
        self.label_14.setText(_translate("Goomba", "Ignition"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Goomba", "Idle"))
        item = self.listWidget.item(1)
        item.setText(_translate("Goomba", "Locate"))
        item = self.listWidget.item(2)
        item.setText(_translate("Goomba", "Forward"))
        item = self.listWidget.item(3)
        item.setText(_translate("Goomba", "Turn: Left"))
        item = self.listWidget.item(4)
        item.setText(_translate("Goomba", "Turn: Right"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pwr.setText(_translate("Goomba", ""))


class WorkerThread(QThread):
    update_progress = pyqtSignal(int) # need to define what kind of signal we want to send
    def run(self):
        # running our process
        # note can't call method in separate class
        # this thread has a finished signal we can catch in main class
        self.update_progress.emit([(1,0),(1,2)])
        # this is where we get each piece of data and send in an ordered manner to gui



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Goomba = QtWidgets.QWidget()
    ui = Ui_Goomba()
    ui.setupUi(Goomba)
    Goomba.show()
    sys.exit(app.exec())
